apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpfoule-deployment
  labels:
    app: helpfoule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helpfoule
  template:
    metadata:
      labels:
        app: helpfoule
    spec:
      containers:
      - name: helpfoule
        image: gaburaisu/node-web-app:latest
        env:
          - name: PORT
            value: "8080"
          - name: MONGODB
            valueFrom:
              secretKeyRef:
                name: helpfoule
                key: mongodb
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: helpfoule
                key: secret
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 512M
          limits:
            cpu: 250m
            memory: 512M
